[workspace]
members = [
    "blocks/evm",
    "common"
]

resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
substreams = "0.5"
substreams-database-change = "1.3"
substreams-ethereum = "0.9"
# substreams-antelope = "0.4"
# substreams-bitcoin = "1.0"
# substreams-near = "0.9"
